 # https://docs.github.com/en/actions/using-workflows/reusing-workflows#creating-a-reusable-workflow
on:
  workflow_call:
    inputs:
      github_environment_name:
        required: true
        type: string

      environment_code:
        required: true
        type: string

      target_url:
        required: true
        type: string
    secrets:
       cloud_username:
         required: true
       cloud_password:
         required: true


jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy on ${{ inputs.target_url }}
        run: |
          if curl -s -H 'X-User-Id: ${{ secrets.cloud_username }}'  -H 'X-Api-Key: ${{ secrets.cloud_password }}' -H 'Content-Type: application/json' -X POST -d '{
              "code":"${{ inputs.environment_code }}",
              "region":"europe-west1.gcp",
              "frontContainerVersion":"${{ github.sha }}"
            }' https://farmer.storefrontcloud.io/instances | grep -q '{"code":200,"result":"Instance updated!"}'; then
            echo "Instance updated"
          else
            echo "Something went wrong during the update process..."
            exit 1
          fi

