 # https://docs.github.com/en/actions/using-workflows/reusing-workflows#creating-a-reusable-workflow
on:
  workflow_call:
    inputs:
      # Example value: demo-magento2-dev
      environment-code: 
        required: true
        type: string

      region:
        required: false
        default: 'europe-west1.gcp'
        type: string

      front-container-version:
        required: false
        default: ${{ github.sha }}
        type: string

      # kebab-case concatenated environment-code, region, and domain
      # Example value: demo-magento2-enterprise-europe-west1-gcp-storefrontcloud-io
      # (very similar to environment URL, https://demo-magento2-enterprise.europe-west1.gcp.storefrontcloud.io)
      namespace: 
        required: true
        type: string

    secrets:
       cloud-username:
         required: true
       cloud-password:
         required: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - run: |
          if curl -s \
             -H 'X-User-Id: ${{ secrets.cloud-username }}' \
             -H 'X-Api-Key: ${{ secrets.cloud-password }}' \
             -H 'Content-Type: application/json' \
             -X POST -d '{
              "code":"${{ inputs.environment-code }}",
              "region":"${{ inputs.region }}",
              "frontContainerVersion":"${{ github.sha }}"
            }' https://farmer.storefrontcloud.io/instances | grep -q '{"code":200,"result":"Instance updated!"}'; then
            echo "Instance updated"
          else
            echo "Something went wrong during the update process..."
            exit 1
          fi

      - name: 'Poll for Farmer pod deployment status'
        timeout-minutes: 5
        run: |
          query_deploy_check_endpoint () {
             curl -s \
              -H 'X-User-Id: ${{ secrets.cloud-username }}' \
              -H 'X-Api-Key: ${{ secrets.cloud-password }}' \
              -H 'Content-Type: application/json' \
              https://farmer.storefrontcloud.io/deploy_check/${inputs.namespace}/${{ inputs.front-container-version }}
          }
          until $( query_deploy_check_endpoint | tee /dev/stderr | grep -q '{"code":200,"ready":"1","deployed":"1"}' ); do
            sleep 10;
          done;
